### ISSUE TITLE
Does parallel_for automatically use a shared memory structure?

### ISSUE THREAD

**Issue by runvnc** [ocaml-multicore/domainslib#12]
Sorry if this is obvious.  Since I am not super-familiar with Ocaml, I could not tell from my casual browsing of the code whether the data for task chunks was being copied to different workers or whether the data was kept in place and just locked when necessary.

I was trying to find an example that used wait() or something to share an array between threads but I didn't.

**Comment by kayceesrk** [comment]
The data isn't copied. They're shared between the domains.
