### ISSUE TITLE
Fast-path for parallel for/reduce/scan when pool has no domains

### ISSUE THREAD

**Issue by sadiqj** [ocaml-multicore/domainslib#15]
In the case where a task pool has no domains in it, we can have a fast path in the `parallel_*` functions which uses serial constructs and avoids the overhead of queuing/dequeuing tasks.

**Comment by Sudha247** [comment]
Addressed for `parallel_scan` too now (cf. f8cea3b251080e464eacb83e27cf6c12f397e2e8).
