### ISSUE TITLE
Error: Unbound module Domain

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-multicore/domainslib#3]
```
# make
dune build @install
File "lib/chan.ml", line 2, characters 42-51:
2 |   | Empty of {receivers: ('a option ref * Domain.id) Fun_queue.t}
                                              ^^^^^^^^^
Error: Unbound module Domain
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by UnixJunkie** [comment]
```
# opam --version
2.0.3
```

**Comment by UnixJunkie** [comment]
```
# which ocaml
~/.opam/4.06.1+multicore/bin/ocaml
```
I am not sure this is really multicore-ocaml that is installed.
Because the prompt tells me 4.10.0.
Despite I nuked my ~/.opam and followed the instructions from
https://github.com/ocaml-multicore/multicore-opam.

Maybe I'll play with this later, when I have more time and once this is a little more mature
(like after the new "real-world OCaml" book version tells us how to use
multicore-ocaml)...

**Comment by kayceesrk** [comment]
I've fixed the `multicore-opam` instructions for opam2.0. The options to install the switch correctly are quite obscure. They're now fixed: https://github.com/ocaml-multicore/multicore-opam#opam-20
