### ISSUE TITLE
possible bug in Task.pool management

### ISSUE THREAD

**Issue by nilsbecker** [ocaml-multicore/domainslib#43]
In the process of experimenting with a domainslib backend for parany I am getting expections `Stdlib.Queue.Empty` raised from Task. I may be doing something wrong but there is a possibility that this is a bug.

I tried to make sure that no domain modifies a global mutable value. Sorry if it's user error nonetheless!

the parany backend is this:

```ocaml
open Domainslib

exception End_of_input

let run ?csize n_cores ~demux ~work ~mux =
  let pool = Task.setup_pool ~num_additional_domains:(n_cores - 1) in
  let csize = Option.value ~default:1 csize in
  let job_queue = ref [] in

  let add_job work_package =
    let job = Task.async pool (fun () ->
        List.rev_map work work_package) in
    job_queue := job :: !job_queue in
  let rec process_all_jobs () =
    let work_package = ref [] in
    try
      for _ = 1 to csize do
        work_package := demux () :: !work_package done;
      add_job !work_package;
      process_all_jobs ()
    with End_of_input ->
      add_job !work_package in

  let collect job =
    let finished_job = Task.await pool job in
    List.iter mux finished_job in

  let rec collect_all_results = function
    | [] -> ()
    | h :: t ->
      collect h; collect_all_results t in

  process_all_jobs ();
  collect_all_results (List.rev !job_queue)
```

the idea is that `demux ()` calls generate a unit of work; these units are collected into work packages of size `csize`; those are then submitted to a `Task.pool` and processed by a function `work`. As soon as available, the accumulated results of chunks of work will be processed by `mux` (e.g. saved to disk) allowing their memory to be freed on-the-fly.

my test (where the module above is called Parany):

```ocaml
let _ = Printexc.record_backtrace true

let max_iterations = 37
let iterations = ref 0
let demux () =
  incr iterations;
  if !iterations <= max_iterations
  then !iterations
  else raise Parany.End_of_input
let work i =
  Unix.sleepf 0.5;
  Format.printf "%d@." i;
  Unix.sleepf 0.05;
  -i
(*let result_queue = Queue.create ()*)
let result_list = ref []
let mux o =
  Format.printf "%d@." o;
  (*Queue.push o result_queue;*)
  result_list := o :: !result_list
let csize = 3
let _ = Parany.run 4 ~csize ~demux ~work ~mux
(*let _ = print_int (Queue.length result_queue)*)
let _ = print_int (List.length !result_list)
let _ = print_newline (); flush_all ()
let _ = Format.(printf "all results in order: %a@."
                  (pp_print_list ~pp_sep:pp_print_space pp_print_int)
```

for me on 4.12+domains with domainslib pinned to 0.3.0 this raises `Stdlib.Queue.Empty` at apparently random degrees of completion of the full task queue.

**Comment by nilsbecker** [comment]
the version below which is somewhat simplified by removing chunking gives the same unexpected behavior (just modify the test file accordingly)
```ocaml
let run_1 n_cores ~demux ~work ~mux =
  let pool = Task.setup_pool ~num_additional_domains:(n_cores - 1) in
  let job_queue = ref [] in

  let add_job work_1 =
    let job = Task.async pool (fun () -> work work_1) in
    job_queue := job :: !job_queue in
  let rec process_all_jobs () =
    try
      let work_1 = demux () in
      add_job work_1;
      process_all_jobs ()
    with End_of_input ->
      () in

  let collect job = Task.await pool job |> mux in

  let rec collect_all_results = function
    | [] -> ()
    | h :: t ->
      collect h; collect_all_results t in

  process_all_jobs ();
  collect_all_results (List.rev !job_queue)
```

**Comment by Sudha247** [comment]
Hi, I tried to run your first test and did not see the exception, it runs find and prints the output.

There was a known bug with `Format` module being called concurrently, that's since been fixed in https://github.com/ocaml-multicore/ocaml-multicore/pull/586. I reckon updating the compiler to the latest commit could actually fix this exception. Please let us know otherwise.

**Comment by nilsbecker** [comment]
thanks for checking. the exception was actually raised only on some runs of the program, from Domainslib.Task: `Raised at Domainslib__Task.await in file "lib/task.ml", line 55, characters 22-29`. so it appeared to have no connection to Format. in any case i will try to pin a newer compiler version and try again.

**Comment by nilsbecker** [comment]
i retried with the current 4.12+domains+effects branch and now i do not get this exception anymore. i also do not see any intermediate strings printed coming from worker domains. all output appears only at the very end of program execution. is this intended? is there a way to get intermediate strings so stdout before child domains join?

**Comment by nilsbecker** [comment]
on further testing i still find unexpected behavior also on the current 4.12+domain+effects branch. 

increasing n_cores to higher values makes the test program hang.  for me, n_cores=13 still works but 14 hangs or segfaults. To reproduce, modify the test program to include this line: `let _ = Parany.run 14 ~csize ~demux ~work ~mux` -- for your machine it may happen at a different value of course. mine is a 10-core iMac.

**Comment by Sudha247** [comment]
I couldn't get the program to segfault or hang. Could you please provide a gdb backtrace for the segfault, if possible?

**Comment by kayceesrk** [comment]
> all output appears only at the very end of program execution. is this intended? is there a way to get intermediate strings so stdout before child domains join?

You can flush the stream explicitly with `%!` format modifier. In particular, the newline `\n` character does not flush the buffer. If you want the output to be printed, you should be able to do:

```ocaml
Format.printf "%d\n%!" 5
```

**Comment by nilsbecker** [comment]
@kayceesrk i thought i had already asked it to flush each time by using `@.` (https://ocaml.org/api/Format.html#fpp) , see the test script above. does only `%!` work in multicore?

@Sudha247 i think gdb will not work for me as i'm on macos. if you can give me a command to invoke on macos i'll gladly send output!

**Comment by kayceesrk** [comment]
can you run the program under `lldb`? 

Also, I'd like to debug the flush issue. The test file seems to have a unclosed paranthesis. Is there a line missing?

**Comment by nilsbecker** [comment]
yes indeed. sorry about that. the last line is
```
                  (List.rev !result_list))
```
i'm trying lldb. so far i get output interactively. i should be able to get it to write to a file.

**Comment by nilsbecker** [comment]
ok, i got a backtrace from lldb saved. it was generated by "bt all" and should contain all threads' stacks
[backtrace.txt](https://github.com/ocaml-multicore/domainslib/files/7185235/backtrace.txt)
.

**Comment by nilsbecker** [comment]
also i should note that the segfault appears also without any calls to Format.

**Comment by kayceesrk** [comment]
That's useful. Thanks for the example. We can rule out Format as the source of the segmentation fault.

**Comment by nilsbecker** [comment]
absolutely. this is the directory with my test project. as i said i ended up using the current 4.12+domains+effects branch as a compiler. the test program ist called scratch.ml; the parany backend implementation is called parany.ml (this is not the original parany, nor the new domainslib based parany recently posted on discuss.ocaml.org)

[domainslibtest.zip](https://github.com/ocaml-multicore/domainslib/files/7190530/domainslibtest.zip)

**Comment by kayceesrk** [comment]
Thanks @nilsbecker. Let me have a look at recreating the bug. I'll be using an MacBook Pro with an i7 processor. Let's see if I can trigger the bug.

**Comment by nilsbecker** [comment]
thanks. for me it was necessary to increase n_cores to some value around 10. for 4 it ran through without errors. just fyi

**Comment by edwintorok** [comment]
As an additional datapoint this segfaults on Linux too using 4.12.0+domains and domainslib.0.3.1 on an AMD  Ryzen 3900X CPU and the instructions from https://github.com/ocaml-multicore/domainslib/issues/43#issuecomment-922364160

```
Core was generated by `./scratch.exe'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  camlDomainslib__Ws_deque__push_356 () at lib/ws_deque.ml:128
128	lib/ws_deque.ml: No such file or directory.
[Current thread is 1 (Thread 0x7f58cfb1af80 (LWP 123062))]
(gdb) bt
#0  camlDomainslib__Ws_deque__push_356 () at lib/ws_deque.ml:128
#1  0x000000000043de44 in camlDomainslib__Multi_channel__send_380 () at lib/multi_channel.ml:113
#2  0x000000000043ebb0 in camlDomainslib__Task__async_627 () at lib/task.ml:65
#3  0x000000000043b1f3 in camlParanyapi__Parany__add_job_143 () at parany.ml:11
#4  0x000000000043b326 in camlParanyapi__Parany__process_all_jobs_212 () at parany.ml:19
#5  0x000000000043b159 in camlParanyapi__Parany__run_89 () at parany.ml:33
#6  0x000000000043af04 in camlDune__exe__Scratch__entry () at scratch.ml:33
#7  0x000000000043820b in caml_program ()
#8  <signal handler called>
#9  0x00000000004b1d6f in caml_startup_common (argv=0x7ffc74351f68, pooling=<optimized out>, pooling@entry=0) at startup_nat.c:133
#10 0x00000000004b1da8 in caml_startup_exn (argv=<optimized out>) at startup_nat.c:137
#11 caml_main (argv=<optimized out>) at startup_nat.c:142
#12 0x0000000000437e4c in main (argc=<optimized out>, argv=<optimized out>) at main.c:41
(gdb) disass
Dump of assembler code for function camlDomainslib__Ws_deque__push_356:
   0x000000000043bde0 <+0>:	lea    -0xe0(%rsp),%r10
   0x000000000043bde8 <+8>:	cmp    0x20(%r14),%r10
   0x000000000043bdec <+12>:	jb     0x43bee6 <camlDomainslib__Ws_deque__push_356+262>
   0x000000000043bdf2 <+18>:	sub    $0x18,%rsp
   0x000000000043bdf6 <+22>:	mov    %rax,%r12
   0x000000000043bdf9 <+25>:	sub    $0x10,%r15
   0x000000000043bdfd <+29>:	cmp    (%r14),%r15
   0x000000000043be00 <+32>:	jb     0x43bedc <camlDomainslib__Ws_deque__push_356+252>
   0x000000000043be06 <+38>:	lea    0x8(%r15),%rax
   0x000000000043be0a <+42>:	mov    %rax,0x8(%rsp)
   0x000000000043be0f <+47>:	movq   $0x400,-0x8(%rax)
   0x000000000043be17 <+55>:	mov    %rbx,(%rax)
=> 0x000000000043be1a <+58>:	mov    0x8(%r12),%rax


info registers
rax            0x7f00001ef7a0      139637978757024
rbx            0x7f00001ef7b0      139637978757040
rcx            0x7f58cfcf7d39      140019420331321
rdx            0x4dccd8            5098712
rsi            0x13                19
rdi            0x7f00001eff80      139637978759040
rbp            0x21757f0           0x21757f0
rsp            0x2175790           0x2175790
r8             0x0                 0
r9             0xffffffff          4294967295
r10            0x21756c8           35083976
r11            0x43b340            4436800
r12            0x3                 3
r13            0x5133a8            5321640
r14            0x7f58cfa80000      140019417743360
r15            0x7f00001ef798      139637978757016
rip            0x43be1a            0x43be1a <camlDomainslib__Ws_deque__push_356+58>
eflags         0x10202             [ IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0

```

`r12` there looks wrong: 0x3 (as if it was NULL pointer + an offset).
r12 originally came from rax (which as since been overwritten), so it looks like it supposed to be the `q` argument to `push`.
And the argument there is from this call, the result of an unsafe array get:
```
  let send mchan v =
    let id = (get_local_state mchan).id in
    Ws_deque.push (Array.unsafe_get mchan.channels id) v;
    check_waiters mchan
```

If I change the unsafe get there to a safe get I get this instead (might be useful to have a debug mode of domainslib that turns all unsafe features into safe features, even if slower?):
```
Fatal error: exception Invalid_argument("index out of bounds")
Raised by primitive operation at Domainslib__Multi_channel.send in file "lib/multi_channel.ml", line 113, characters 16-45
Called from Domainslib__Task.async in file "lib/task.ml", line 65, characters 2-48
Called from Paranyapi__Parany.run.add_job in file "parany.ml", line 11, characters 14-80
Called from Paranyapi__Parany.run.process_all_jobs in file "parany.ml", line 19, characters 6-27
Called from Paranyapi__Parany.run in file "parany.ml", line 33, characters 2-21
Called from Dune__exe__Scratch in file "scratch.ml", line 33, characters 8-45
```

With a bit more printfs:
```
Bad channel id 12 >= 4
```

Adding a `Task.teardown_pool pool` in each of Parany.run* functions seems to fix the issue, it is as if an async registered on one pool tried to run on another pool? (the initial pool had 16 channel ids, whereas the 2nd pool only has 4).

I think this might be because without a teardown_pool the domains would already have an ID assigned, by the previous *smaller* pool, and thus inadvertently some global state leaks from one pool to another (and seems to imply that it is only safe to use one pool at a time with domainslib currently).
It looks like the `dls_key` in Multi_channel is global, whereas it should really be per-pool (or in this case, per multi-channel) instead.

**Comment by edwintorok** [comment]
@kayceesrk hope you don't mind I opened a PR with a possible fix.

**Comment by kayceesrk** [comment]
Thanks very much for the PR! Much appreciated :-)
