### ISSUE TITLE
Move `ws_deque` to lockfree

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/domainslib#48]
The work-stealing deque in domainslib [1] seems useful to have outside of domainslib. We should perhaps move this to `ocaml-multicore/lockfree` and make `domainslib` depend on `lockfree`?

Also, I'd archive the current `lockfree` library and start afresh since the current implementation predates the OCaml memory model [2].

[1] https://github.com/ocaml-multicore/domainslib/blob/master/lib/ws_deque.ml
[2] https://kcsrk.info/papers/pldi18-memory.pdf

**Comment by jmid** [comment]
This is addressed with the release of lockfree 0.2.0 and #70
